### ISSUE TITLE
Hello, Im trying to uninstall Tiramizoo plugin and having errors when browsing to all categories

### ISSUE THREAD

**Issue by kerromatic** [tiramizoo/magento-plugin#1]
after I uninstall and attempt to navigate to manage categories I get a lengthy error message and I am not able to go into the manage categories unless I re install the extension.

**Comment by kowalikus** [comment]
Which version of Magento are You using?

2015-05-19 1:46 GMT+02:00 kerromatic notifications@github.com:

> after I uninstall and attempt to navigate to manage categories I get a
> lengthy error message and I am not able to go into the manage categories
> unless I re install the extension.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tiramizoo/magento-plugin/issues/1.

## 

Krzysztof Kowalik
ageno.pl
krzysztof.kowalik@ageno.pl
+48 508 411 677

**Comment by kerromatic** [comment]
Hello, I am using version 1.8.1.0

Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone-------- Original message --------

**Comment by kowalikus** [comment]
We are going to check this issue.

2015-05-19 15:44 GMT+02:00 kerromatic notifications@github.com:

> Hello, I am using version 1.8.1.0
> 
> Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone--------
> Original message --------
> From: kowalikus notifications@github.com
> Date: 05/19/2015 12:59 AM (GMT-05:00)
> To: tiramizoo/magento-plugin magento-plugin@noreply.github.com
> Cc: kerromatic kerromatic@gmail.com
> Subject: Re: [magento-plugin] Hello, Im trying to uninstall Tiramizoo
> plugin
> and having errors when browsing to all categories (#1)
> 
> Which version of Magento are You using?
> 
> 2015-05-19 1:46 GMT+02:00 kerromatic notifications@github.com:
> 
> > after I uninstall and attempt to navigate to manage categories I get a
> > 
> > lengthy error message and I am not able to go into the manage categories
> > 
> > unless I re install the extension.
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/tiramizoo/magento-plugin/issues/1.
> 
> ## 
> 
> Krzysztof Kowalik
> 
> ageno.pl
> 
> krzysztof.kowalik@ageno.pl
> 
> +48 508 411 677
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tiramizoo/magento-plugin/issues/1#issuecomment-103499738
> .

## 

Krzysztof Kowalik
ageno.pl
krzysztof.kowalik@ageno.pl
+48 508 411 677

**Comment by kowalikus** [comment]
Unfortunatelly Magento didn't support uninstall script for module. You can read about this issue [here](http://www.codeitive.com/0QyjXkVVkk/magento-extension-development-deal-with-uninstall.html).

After Tiramizoo module uninstalling. You need to run the following query at Your database:

``` sql
DELETE FROM eav_attribute WHERE `attribute_code` IN ('tiramizoo_enable', 'tiramizoo_category_enable', 'tiramizoo_packed_individually', 'trmz_cat_packed_individually');

```
